version: '3'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.7.1-python3.9
  environment:
  - PYTHONPATH=/opt/airflow
  env_file:
    - airflow.env
  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./etls:/opt/airflow/etls
    - ./logs:/opt/airflow/logs
    - ./pipelines:/opt/airflow/pipelines
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests
    - ./utils:/opt/airflow/utils
   # - ./airflow.cfg:/opt/airflow/airflow.cfg
    - ./requirements.txt:/opt/airflow/requirements.txt
  depends_on:
    - postgres
    - redis

services:
  mysql:
    image: mysql:8.0  # Chọn phiên bản MySQL, ví dụ 8.0
    container_name: mysql_container  # Tên container MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Mật khẩu cho user root
      MYSQL_DATABASE: airflow_db          # Tên database mặc định
      MYSQL_USER: airflow_user            # Tạo user mới
      MYSQL_PASSWORD: airflow_password    # Mật khẩu cho user mới
    ports:
      - "3307:3306"  # Mở cổng 3306 để truy cập MySQL từ host
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu MySQL
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_reddit
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: airflow_user
      PMA_PASSWORD: airflow_password
    ports:
      - "8081:80"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt && airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8082:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker

volumes:
  mysql_data:
    driver: local